title: PorcupineBee Blog
description: A blog with guides and tutorials on Linux, WSL, and Seismic Unix
author: Shanu Biswas
keywords: [linux, wsl, seismic unix, tutorials, tech blog]
theme: jekyll-theme-cayman